language: java
jdk:
  - openjdk7
env:
  global:
    - secure: "VK+IqyTFmEf5sv8OYOa6vLqcs0SAjC/ODklIDs0rr1zU/w21mZI2eH1w5YVk\ngwWA1QR7JOxWM6S9ED4NqHymK6QOj85W4FUv0seRv5LGJ1ATAUSzyElP0BXS\n46XsROFj9itTRwZkLdFaGGO14PRAQAznS6XM22uyQO3dg1wB4bQ="
    - secure: "ngfDTSbLJ9suMJ+hUJws7wKbP184+Poyd09Rc3MEdpD8oq2mW8+XYi1bjmnA\n04bxqQ+hnLCdxjVqaXjp7nMB8pCHxWaraoOyU1uJJxFSNO1y1f2k09eAexA+\nLN4fXIU8HjPLvXz2u8oZITYCWKuCyAIuiFus7N9RZ+Kk/mYE0lg="
    - secure: "YDLYUZiLuoNCRpdIMxycacPOyJkIw/lfycpEiIfoyuVQCTf0Sig/KZpjDyHj\nlU8gPqwYewp//lTyczuJIFq8IOghO3QejGaqlNGNLOmFPIsfdThMGOYn9IOJ\nkqO4enPLfxjnEAxvcKQDboUrCETjsimCvMccgIZDcvlQ6iFAdzA="
  matrix:
    - ECLIPSE_TARGET=kepler
install: true
before_install:
  # Maven 3.1.1
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar xvf apache-maven-3.1.1-bin.tar.gz > /dev/null
  - export MVN_HOME=`pwd`/apache-maven-3.1.1
  - export PATH=${MVN_HOME}/bin/:${PATH}
  - mvn --version
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  - sudo apt-get update
  - sudo apt-get install -qq metacity
  - metacity --sm-disable --replace &
  - sleep 5 # give xvfb some time to start
  - export QUALIFIER=travis$(printf "%0*d" 6 ${TRAVIS_BUILD_NUMBER})-${TRAVIS_BRANCH}-git${TRAVIS_COMMIT}
script: mvn clean verify --batch-mode -e -DforceContextQualifier=${QUALIFIER}
after_success: 
  - test ${ECLIPSE_TARGET} = "kepler" && chmod 777 ./scripts/travis-deploy.sh && ./scripts/travis-deploy.sh
after_failure:
  - chmod 777 ./scripts/travis-test-report.sh && ./scripts/travis-test-report.sh
