sudo: true # explicitly ask for using the new docker-based infrastructure

branches:
  except:
    # workaround to prevent version tags from being built in addition to the build commit
    - /^v?[0-9]/

language: java

jdk:
  - openjdk7

env:
  global:
    - secure: "VK+IqyTFmEf5sv8OYOa6vLqcs0SAjC/ODklIDs0rr1zU/w21mZI2eH1w5YVk\ngwWA1QR7JOxWM6S9ED4NqHymK6QOj85W4FUv0seRv5LGJ1ATAUSzyElP0BXS\n46XsROFj9itTRwZkLdFaGGO14PRAQAznS6XM22uyQO3dg1wB4bQ="
    - secure: "ngfDTSbLJ9suMJ+hUJws7wKbP184+Poyd09Rc3MEdpD8oq2mW8+XYi1bjmnA\n04bxqQ+hnLCdxjVqaXjp7nMB8pCHxWaraoOyU1uJJxFSNO1y1f2k09eAexA+\nLN4fXIU8HjPLvXz2u8oZITYCWKuCyAIuiFus7N9RZ+Kk/mYE0lg="
    - secure: "YDLYUZiLuoNCRpdIMxycacPOyJkIw/lfycpEiIfoyuVQCTf0Sig/KZpjDyHj\nlU8gPqwYewp//lTyczuJIFq8IOghO3QejGaqlNGNLOmFPIsfdThMGOYn9IOJ\nkqO4enPLfxjnEAxvcKQDboUrCETjsimCvMccgIZDcvlQ6iFAdzA="
  matrix:
    - ECLIPSE_TARGET=luna

install: true

cache:
  directories:
    - ${HOME}/.m2

before_script:
  - "export DISPLAY=:99.0" # ou mettre dans env: DISPLAY=:99 see https://github.com/mozilla/mozmill/pull/116/files
  - echo "#-#-#-# starting xvfb "
  - date
  - "sh -e /etc/init.d/xvfb start"
  - echo "#-#-#- xvfb started"
  - date
  - sleep 5 # give xvfb some time to start
#  - sudo apt-get install fluxbox
#  - fluxbox &
#  - sleep 5 # give fluxbox some time to start
  - echo "#-#-#-# installling metacity"
  - date
  - sudo apt-get update
  - sudo apt-get install -qq metacity
  - metacity --sm-disable --replace &
  - echo "#-#-#-# metacity installed"
  - date
  - sleep 5 # give metacity some time to start
  - export QUALIFIER=CI$(printf "%0*d" 6 ${TRAVIS_BUILD_NUMBER})-${TRAVIS_BRANCH}-git${TRAVIS_COMMIT}
  - export BRANCH=${TRAVIS_BRANCH}
script: 
  - echo "#-#-#-# calling maven "
  - date
  - mvn clean verify --batch-mode -e -DforceContextQualifier=${QUALIFIER}
  - echo "#-#-#-# maven called"
  - date
after_success: 
  - test ${ECLIPSE_TARGET} = "luna" && test ${TRAVIS_SECURE_ENV_VARS} && chmod 777 ./scripts/travis-deploy.sh
  - test ${ECLIPSE_TARGET} = "luna" && test ${TRAVIS_SECURE_ENV_VARS} && echo "#-#-#-#- deploying " 
  - test ${ECLIPSE_TARGET} = "luna" && test ${TRAVIS_SECURE_ENV_VARS} && date
  - test ${ECLIPSE_TARGET} = "luna" && test ${TRAVIS_SECURE_ENV_VARS} && ./scripts/travis-deploy.sh
  - test ${ECLIPSE_TARGET} = "luna" && test ${TRAVIS_SECURE_ENV_VARS} && echo "#-#-#-#- deployed "
  - test ${ECLIPSE_TARGET} = "luna" && test ${TRAVIS_SECURE_ENV_VARS} && echo date
after_failure:
  - test ${TRAVIS_SECURE_ENV_VARS} && chmod 777 ./scripts/travis-test-report.sh && ./scripts/travis-test-report.sh
